#!/usr/bin/env sh

# Farben für die Ausgabe
YELLOW='\033[1;33m'
NC='\033[0m'

# Backup-Konfiguration
export ZSTD_CLEVEL=9
export ZSTD_NBTHREADS=2
backupDate=$(date '+%d%m%y')

# Docker-Container stoppen
for dir in docker/*
do
    pushd ${dir}
    docker-compose down
    popd
done

sleep 15

# Backup erstellen
pushd "$HOME"
sudo tar --create --sparse --zstd --file docker-backup-$backupDate.tar.zst --checkpoint=.100 docker
popd

sleep 15

# Docker-Container wieder starten
for dir in docker/*
do
    pushd ${dir}
    docker-compose up -d
    popd
done

# Nur die drei neuesten Backups behalten
backup_dir="$HOME"

setopt NULL_GLOB

backups=("${backup_dir}"/docker-backup-*.tar.zst(On))

if (( ${#backups[@]} > 3 )); then
    for file in "${backups[@]:3}"; do
        echo "Lösche altes Backup: $file"
        rm -f -- "$file"
    done
else
    echo "Nur ${#backups[@]} Backup(s) vorhanden – nichts zu löschen."
fi

echo "${YELLOW}Backup abgeschlossen.${NC}"
