#!/usr/bin/env sh

# Farben für die Ausgabe
YELLOW='\033[1;33m'
NC='\033[0m'

# Backup-Konfiguration
export ZSTD_CLEVEL=9
export ZSTD_NBTHREADS=2
username=$(whoami)
backupDate=$(date '+%d%m%y')

# Docker-Container stoppen
for dir in docker/*
do
    pushd ${dir}
    docker-compose down
    popd
done

sleep 15

# Backup erstellen
pushd /home/$username
sudo tar --create --sparse --zstd --file docker-backup-$backupDate.tar.zst --checkpoint=.100 docker
popd

sleep 15

# Docker-Container wieder starten
for dir in docker/*
do
    pushd ${dir}
    docker-compose up -d
    popd
done

# Nur die drei neuesten Backups behalten
backup_dir="/home/$username"
ls -1t "${backup_dir}"/docker-backup-*.tar.zst 2>/dev/null | tail -n +4 | while read -r file; do
    rm -- "$file"
    echo "Lösche altes Backup: $file"
done

echo "${YELLOW}Backup abgeschlossen.${NC}"
